using Microsoft.CodeAnalysis;
using System;

namespace RemoveOnly
{
    [Generator("C#")]
    public class RemoveOnlyGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForPostInitialization(static context =>
            {
                context.AddSource(
                    "GlobalUsings.cs",
                    @"// <auto-generated />
#if NET6_0_OR_GREATER
global using Date = System.DateOnly;
global using Time = System.TimeOnly;
#endif
");
            });
        }
    }
}
